name: Clear Deployments

on: 
  workflow_dispatch:
  
permissions:
  deployments: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: 배포(Deployments) 기록 싹 지우기
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages 
          onlyRemoveDeployments: true
