name: Clean Deployments

on: 
  workflow_dispatch: 
  deployment_status: 

permissions:
  deployments: write

jobs:
  cleanup:
    if: github.event_name == 'workflow_dispatch' || (github.event.deployment.environment == 'github-pages' && github.event.deployment_status.state == 'success')
    runs-on: ubuntu-latest
    steps:
      - name: 배포(Deployments) 기록 싹 지우기
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          environment: github-pages 
          onlyRemoveDeployments: true
