name: ProjectMX Crawler

on:
  schedule:
    - cron: '24 * * * *' 
  workflow_dispatch:

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
    - name: 코드 가져오기
      uses: actions/checkout@v4

    - name: Go 언어 환경 셋업
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: 크롤러 실행 및 R2 자동 업로드
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        CF_ACCESS_KEY_ID: ${{ secrets.CF_ACCESS_KEY_ID }}
        CF_SECRET_ACCESS_KEY: ${{ secrets.CF_SECRET_ACCESS_KEY }}
        CF_BUCKET_NAME: ${{ secrets.CF_BUCKET_NAME }}
        TZ: Asia/Seoul
      run: |
        cd scripts 
        
        go mod init crawler || true
        go mod tidy
        
        go run dc_crawling.go
